CREATE TABLE  DB.COMPANY_MAILER_USER 
   (ID INT NOT NULL, 
	NAME VARCHAR(100), 
	EMAIL VARCHAR(100), 
	PASSWORD VARCHAR(100), 
	GENDER VARCHAR(100), 
	DOB DATE, 
	ADDRESSLINE VARCHAR(100), 
	CITY VARCHAR(100), 
	STATE VARCHAR(100),
	COUNTRY VARCHAR(100), 
	CONTACT VARCHAR(100), 
	REGISTEREDDATE DATE, 
	AUTHORIZED VARCHAR(100), 
	PRIMARY KEY (ID)
   );


CREATE TABLE  DB.COMPANY_MAILER_MESSAGE 
   (ID INT NOT NULL, 
	SENDER VARCHAR(100), 
	RECEIVER VARCHAR(100), 
	SUBJECT VARCHAR(100), 
	MESSAGE VARCHAR(100), 
	TRASH VARCHAR(100), 
	MESSAGEDATE DATE, 
	PRIMARY KEY (ID)
   );
